In [1]:
import os
import numpy as np   
import sklearn
import keras
from sklearn.preprocessing import minmax_scale

Using TensorFlow backend.


In [3]:
import pandas as pd

In [4]:
train_data = pd.read_csv('../../input/train.csv')
test_data = pd.read_csv('../../input/test.csv')

In [5]:
id_list, id_indexes = np.unique(train_data['KPI ID'], return_index=True)
id_indexes.sort()
id_indexes = np.append(id_indexes, len(train_data))   
timeseries_all = []
timeseries_label = []

for i in np.arange(len(id_indexes)-1):
    timeseries_all.append(np.asarray(train_data['value'][id_indexes[i]:id_indexes[i+1]]))
    timeseries_label.append(np.asarray(train_data['label'][id_indexes[i]:id_indexes[i+1]]))
print(timeseries_all)
print(timeseries_label)

[array([1.90163934, 1.78688526, 2.        , ..., 2.61403513, 2.73684216,
       2.4912281 ]), array([27.23077011, 29.84615326, 28.61538506, ..., 37.25      ,
       36.66666794, 37.        ]), array([1.66666663, 1.83333337, 1.75      , ..., 5.        , 4.91666651,
       4.66666651]), array([0., 0., 0., ..., 0., 0., 0.]), array([2.25      , 3.1500001 , 3.04999995, ..., 5.44999981, 6.80000019,
       5.69999981]), array([9.13373376e+08, 9.01925824e+08, 9.15506240e+08, ...,
       9.60516800e+08, 9.61848768e+08, 9.62367296e+08]), array([1.06734995e+09, 1.05601555e+09, 1.05589376e+09, ...,
       1.00463066e+09, 1.09299085e+09, 1.08772019e+09]), array([1204.625 , 1182.25  , 1155.1875, ..., 1371.375 , 1381.0625,
       1376.9375]), array([ 0.83281839, -0.04328661,  0.06622652, ...,  0.50427902,
        0.61379214,  0.50427902]), array([0.19757504, 0.14987727, 0.07889324, ..., 0.08827026, 0.09042697,
       0.07923706]), array([-1.04808758, -1.01906734, -0.96832112, ...,  1.03450159,
      

In [6]:
sum1 = 0
for i in range(26):
    for j in range(len(timeseries_all[i])):
        if abs(timeseries_all[i][j] - train_data['value'][sum1+j])>1e-6:
            print(i,j,timeseries_all[i][j],train_data['value'][sum1+j])
        if timeseries_label[i][j] != train_data['label'][sum1+j]:
            print(i,j,timeseries_label[i][j],train_data['label'][sum1+j])
    sum1 += len(timeseries_all[i])


In [7]:
test_id_list, test_id_indexes = np.unique(test_data['KPI ID'], return_index=True)
test_id_indexes.sort()
test_id_indexes = np.append(test_id_indexes, len(test_data))   
testseries_all = []

for i in np.arange(len(test_id_indexes)-1):
    testseries_all.append(np.asarray(test_data['value'][test_id_indexes[i]:test_id_indexes[i+1]]))
print(testseries_all)

[array([2.71929836, 2.45614028, 2.33333325, ..., 1.46753252, 1.44155848,
       1.4545455 ]), array([36.58333206, 35.83333206, 36.58333206, ..., 22.83333397,
       22.66666603, 22.08333397]), array([4.91666651, 4.91666651, 4.75      , ..., 2.        , 2.        ,
       2.        ]), array([0., 0., 0., ..., 0., 0., 0.]), array([5.        , 5.5       , 5.1500001 , ..., 3.5       , 3.8499999 ,
       2.79999995]), array([9.63912960e+08, 9.64395008e+08, 1.03828864e+09, ...,
       1.18040589e+09, 1.17810714e+09, 1.17690176e+09]), array([1.08574938e+09, 1.07270912e+09, 1.06353952e+09, ...,
       9.30710976e+08, 9.27908288e+08, 9.30293248e+08]), array([1414.8125  , 1343.8125  , 1367.4375  , ..., 1463.705933,
       1487.529419, 1431.411743]), array([ 0.61379214,  0.72330527,  0.72330527, ...,  0.06622652,
       -0.04328661, -0.26231286]), array([ 0.08339421,  0.07542374,  0.07589259, ..., -0.29456217,
       -0.29134273, -0.28743564]), array([0.8444066 , 0.40438471, 0.92587745, ..., 0.12

In [428]:
file = open('train_test_all.txt','wb')
pickle.dump(timeseries_all,file)
pickle.dump(timeseries_label,file)
pickle.dump(testseries_all,file)
file.close()

In [429]:
for i in range(len(timeseries_all)):
    print(len(timeseries_all[i]),len(testseries_all[i]))

128562 112627
128613 110185
129035 112113
128679 108747
129128 111171
128971 111004
128667 112786
128853 112116
8784 8784
10960 10960
8248 8249
8247 8248
8784 8784
8784 8784
8784 8784
147024 147024
147009 147010
100254 108901
147629 147629
147668 147669
147689 147690
137925 137925
129453 129454
147680 147681
65449 65450
65436 65436


In [8]:
sum1 = 0
for i in range(26):
    print(i)
    for j in range(len(testseries_all[i])):
        if abs(testseries_all[i][j] - test_data['value'][sum1+j])>1e-6:
            print(i,j,testseries_all[i][j],test_data['value'][sum1+j])
    sum1 += len(testseries_all[i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [9]:
timeseries_scaled = []
for i in range(len(timeseries_all)):
    timeseries_scaled.append(minmax_scale(timeseries_all[i]))
print(timeseries_scaled)
print(len(timeseries_scaled))

[array([0.16579029, 0.15009279, 0.17924528, ..., 0.26324065, 0.28003973,
       0.24644158]), array([0.25469729, 0.28511779, 0.27080227, ..., 0.37123471, 0.36444976,
       0.36832687]), array([0.08658008, 0.0952381 , 0.09090909, ..., 0.25974026, 0.25541125,
       0.24242423]), array([0., 0., 0., ..., 0., 0., 0.]), array([0.00440788, 0.00617103, 0.00597512, ..., 0.01067685, 0.01332158,
       0.01116662]), array([0.36525055, 0.35480202, 0.36719728, ..., 0.4082798 , 0.40949553,
       0.40996881]), array([0.4686479 , 0.4575223 , 0.45740275, ..., 0.40708398, 0.49381646,
       0.4886429 ]), array([0.03054516, 0.02918036, 0.02752964, ..., 0.04071636, 0.04130726,
       0.04105565]), array([0.58974359, 0.38461538, 0.41025641, ..., 0.51282051, 0.53846154,
       0.51282051]), array([0.38908621, 0.37983683, 0.36607186, ..., 0.36789022, 0.36830844,
       0.36613853]), array([0.2827225 , 0.28839568, 0.2983161 , ..., 0.68984923, 0.63849842,
       0.68498243]), array([0.47658635, 0.45154548, 

In [10]:
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt
def get_feature_logs(time_series):
    return np.log(time_series + 1e-2)
def get_feature_SARIMA_residuals(time_series):
    predict = SARIMAX(time_series,
                      trend='n', 
                      order=(5,1,1), 
                      measurement_error=True).fit().get_prediction()
    return time_series - predict.predicted_mean

def get_feature_AddES_residuals(time_series):
    predict = ExponentialSmoothing(time_series, trend='add').fit(smoothing_level=1)
    return time_series - predict.fittedvalues

def get_feature_SimpleES_residuals(time_series):
    predict = SimpleExpSmoothing(time_series).fit(smoothing_level=1)
    return time_series - predict.fittedvalues

def get_feature_Holt_residuals(time_series):
    predict = Holt(time_series).fit(smoothing_level=1)
    return time_series - predict.fittedvalues

In [11]:
def get_timeseries_features(time_series, time_series_label, Windows, delay):
  
    data = []
    data_label = []
    data_label_vital = []
    
    start_point = 2*max(Windows) - 1
    start_accum = sum(time_series[0:start_point])
    
    time_series_AddES_residuals = get_feature_AddES_residuals(time_series)
    time_series_SimpleES_residuals = get_feature_SimpleES_residuals(time_series)
    time_Series_Holt_residuals = get_feature_Holt_residuals(time_series)
    
    time_series_logs = get_feature_logs(time_series)
    
    for i in np.arange(start_point, len(time_series)):        
        datum = []
        datum_label = time_series_label[i]        
        
        diff_plain = time_series[i] - time_series[i-1]
        start_accum = start_accum + time_series[i]
        mean_accum = (start_accum)/(i+1)
        
        datum.append(time_series_AddES_residuals[i])
        datum.append(time_series_SimpleES_residuals[i])
        datum.append(time_Series_Holt_residuals[i])

        datum.append(time_series_logs[i])
        

        datum.append(diff_plain)
        
        datum.append(diff_plain/(time_series[i-1] + 1e-8))  

        datum.append(diff_plain - (time_series[i-1] - time_series[i-2]))
 
        datum.append(time_series[i] - mean_accum)


        for k in Windows:
            mean_w = np.mean(time_series[i-k+1:i+1])
            var_w = np.mean((np.asarray(time_series[i-k+1:i+1]) - mean_w)**2)
 
            
            mean_w_and_1 = mean_w + (time_series[i-k]-time_series[i])/k
            var_w_and_1 = np.mean((np.asarray(time_series[i-k:i]) - mean_w_and_1)**2)

            
            mean_2w = np.mean(time_series[i-2*k+1:i-k+1])
            var_2w = np.mean((np.asarray(time_series[i-2*k+1:i-k+1]) - mean_2w)**2)
            
            
            diff_mean_1 = mean_w - mean_w_and_1
            diff_var_1 = var_w - var_w_and_1
            
            diff_mean_w = mean_w - mean_2w
            diff_var_w = var_w - var_2w
            
            datum.append(mean_w)  
            
            datum.append(var_w)
            
            datum.append(diff_mean_1)
            
            datum.append(diff_mean_1/(mean_w_and_1 + 1e-8))
            
            datum.append(diff_var_1)
            
            datum.append(diff_var_1/(var_w_and_1 + 1e-8))
            
            datum.append(diff_mean_w)
            
            datum.append(diff_mean_w/(mean_2w + 1e-8))
            
            datum.append(diff_var_w)
            
            datum.append(diff_var_w/(var_2w + 1e-8))
            
            
            datum.append(time_series[i] - mean_w_and_1)
            
            datum.append(time_series[i] - mean_2w)

        data.append(np.asarray(datum))
        data_label.append(np.asarray(datum_label))

        if datum_label == 1 and sum(time_series_label[i-delay:i]) < delay:
            data_label_vital.append(np.asarray(1))
        else:
            data_label_vital.append(np.asarray(0))
            
    return data, data_label, data_label_vital

In [12]:
from sklearn.preprocessing import StandardScaler
import random

In [13]:
W = np.asarray([2, 5, 10, 25, 50, 100, 200, 300, 400, 500])
delay = 7
scaler_list = [] 
timeseries_features = None
timeseries_features_label = []
timeseries_features_label_vital = []

for i in range(len(timeseries_all)):
    features_temp,label_temp,label_vital_temp = get_timeseries_features(timeseries_scaled[i], timeseries_label[i], W, delay) 
    print(i)
    assert(len(features_temp)==len(label_temp))
    assert(len(label_temp) == len(label_vital_temp))
    scaler_temp = StandardScaler()
    features_temp = scaler_temp.fit_transform(features_temp)
    scaler_list.append(scaler_temp)
    if i==0:
        timeseries_features = features_temp
    else:
        timeseries_features = np.concatenate((timeseries_features, features_temp), axis = 0)
        
    timeseries_features_label = timeseries_features_label + label_temp
    timeseries_features_label_vital = timeseries_features_label_vital + label_vital_temp



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [14]:
print(timeseries_features.shape)
print(len(timeseries_features_label),len(timeseries_features_label_vital))

(2450341, 128)
2450341 2450341


In [16]:
import pickle
timeseries_features_label = np.array(timeseries_features_label)
timeseries_features_label_vital = np.array(timeseries_features_label_vital)
file = open('timeseries_features2.txt','wb')
pickle.dump(timeseries_features,file)
pickle.dump(scaler_list,file)
pickle.dump(timeseries_features_label,file)
pickle.dump(timeseries_features_label_vital,file)
file.close()


In [17]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Activation
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

np.random.seed(5)

In [18]:
model = Sequential()
model.add(Dense(256, input_dim = 128))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(128))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(1))
model.add(BatchNormalization())
model.add(Activation('sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy','binary_accuracy'])





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [19]:
print(sum(timeseries_features_label))
print(sum(timeseries_features_label_vital))

53219
4853


In [21]:
ratio = round((len(timeseries_features_label) - sum(timeseries_features_label)) / sum(timeseries_features_label))
print(ratio)
non_anomaly = np.ones(len(timeseries_features_label)) - timeseries_features_label
print(non_anomaly,non_anomaly.shape)
sample_ratio = (4*ratio) * timeseries_features_label_vital + non_anomaly
print(sample_ratio,sum(sample_ratio))
sample_ratio = sample_ratio + ratio * timeseries_features_label
print(sample_ratio,sum(sample_ratio))

45.0
[1. 1. 1. ... 0. 0. 0.] (2450341,)
[1. 1. 1. ... 0. 0. 0.] 3270662.0
[ 1.  1.  1. ... 45. 45. 45.] 5665517.0


In [22]:
import time
print('Keras: start to train DNN!')
start_time = time.time()
history = model.fit(timeseries_features, timeseries_features_label, epochs=100, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!



Epoch 1/100





2450341/2450341 [==============================] - 38s 16us/step - loss: 0.8567 - acc: 0.7551 - binary_accuracy: 0.7551
Epoch 2/100
2450341/2450341 [==============================] - 33s 13us/step - loss: 0.6455 - acc: 0.8543 - binary_accuracy: 0.8543
Epoch 3/100
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.5439 - acc: 0.9000 - binary_accuracy: 0.9000
Epoch 4/100
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.4758 - acc: 0.9204 - binary_accuracy: 0.9204
Epoch 5/100
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.4319 - acc: 0.9332 - binary_accuracy: 0.9332
Epoch 6/100
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.4051 - acc: 0.9399 - binary_accuracy: 0.9399
Epoch 7/100
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.3802 - acc: 0.9465 - binary_accuracy: 0.9465
Epoch 8/100
2450341/2450341 [============

In [23]:
file = open('model2.txt','wb')
pickle.dump(model,file)
pickle.dump(history,file)
file.close()

In [24]:
file = open('test_features2.txt','rb')
testseries_features = pickle.load(file)
file.close()

In [69]:
train_data_check = np.ravel(model.predict(timeseries_features, batch_size=5000,verbose=1)>0.96).astype(int)
print(train_data_check)
print(precision_score(timeseries_features_label, train_data_check))
print(recall_score(timeseries_features_label, train_data_check))
print(f1_score(timeseries_features_label, train_data_check))

2450341/2450341 [==============================] - 7s 3us/step
[0 0 0 ... 1 1 1]
0.9467576404770455
0.9412427892294105
0.9439921604100708


In [48]:
predict_flag = (np.ravel(model.predict(testseries_features,batch_size=5000,verbose=1))>0.9999999).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

2319237/2319237 [==============================] - 7s 3us/step
[0 0 0 ... 0 0 0]
0.10650830423971332


In [32]:
data_features_diff = len(test_data) - len(testseries_features)
print(data_features_diff)
data_features_diff_avg = int(data_features_diff / len(testseries_all))
print(data_features_diff_avg)

25974
999


In [49]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictn.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [36]:
print(sum(train_data_check)/len(train_data_check))

0.02624451045793218


In [50]:
testseries_scaled = []
for i in range(len(testseries_all)):
    testseries_scaled.append(minmax_scale(testseries_all[i]))
print(testseries_scaled)
print(len(testseries_scaled))

[array([0.3932252 , 0.35421474, 0.33600987, ..., 0.20766387, 0.20381349,
       0.20573868]), array([0.3546042 , 0.34733441, 0.3546042 , ..., 0.22132473, 0.21970921,
       0.21405494]), array([0.30256409, 0.30256409, 0.29230769, ..., 0.12307692, 0.12307692,
       0.12307692]), array([0., 0., 0., ..., 0., 0., 0.]), array([0.00931793, 0.01024972, 0.00959747, ..., 0.00652255, 0.0071748 ,
       0.00521804]), array([0.45261198, 0.45309328, 0.52687281, ..., 0.66877059, 0.66647539,
       0.66527187]), array([0.4822847 , 0.46993302, 0.4612476 , ..., 0.33543289, 0.33277819,
       0.33503722]), array([0.15237441, 0.14472776, 0.14727216, ..., 0.15764021, 0.16020598,
       0.15416214]), array([0.52380952, 0.54761905, 0.54761905, ..., 0.4047619 , 0.38095238,
       0.33333333]), array([0.45257122, 0.45066495, 0.45077709, ..., 0.36217659, 0.36294657,
       0.36388102]), array([0.42934343, 0.40162322, 0.43447588, ..., 0.38412757, 0.38893099,
       0.3898104 ]), array([0.23961237, 0.23312242, 

In [51]:
print(scaler_list)

[StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScaler(copy=True, with_mean=True, with_std=True), StandardScale

In [52]:
id_t1, id_t2 = np.unique(train_data['KPI ID'], return_index=True)
print(id_t1,id_t2)

['02e99bd4f6cfb33f' '046ec29ddf80d62e' '07927a9a18fa19ae'
 '09513ae3e75778a3' '18fbb1d5a5dc099d' '1c35dbf57f55f5e4'
 '40e25005ff8992bd' '54e8a140f6237526' '71595dd7171f4540'
 '769894baefea4e9e' '76f4550c43334374' '7c189dd36f048a6c'
 '88cf3a776ba00e7c' '8a20c229e9860d0c' '8bef9af9a922e0b3'
 '8c892e5525f3e491' '9bd90500bfd11edb' '9ee5879409dccef9'
 'a40b1df87e3f1c87' 'a5bf5d65261d859a' 'affb01ca2b4f0b45'
 'b3b2e6d1a791d63a' 'c58bfcbacb2822d1' 'cff6d3c01e6a6bfa'
 'da403e4e3f87c9e0' 'e0770391decc44ce'] [      0 1030508 1039292  644017  514889  901655 1387132 1050252 1635015
 1075531 1084315 1782683 2410879 1066747 2068297 1240123  128562 2345430
 1930372  386210 2197750 1058500  772988 1487386  257175 1093099]


In [53]:
id_t3, id_t4 = np.unique(test_data['KPI ID'], return_index=True)
print(id_t3,id_t4)

['02e99bd4f6cfb33f' '046ec29ddf80d62e' '07927a9a18fa19ae'
 '09513ae3e75778a3' '18fbb1d5a5dc099d' '1c35dbf57f55f5e4'
 '40e25005ff8992bd' '54e8a140f6237526' '71595dd7171f4540'
 '769894baefea4e9e' '76f4550c43334374' '7c189dd36f048a6c'
 '88cf3a776ba00e7c' '8a20c229e9860d0c' '8bef9af9a922e0b3'
 '8c892e5525f3e491' '9bd90500bfd11edb' '9ee5879409dccef9'
 'a40b1df87e3f1c87' 'a5bf5d65261d859a' 'affb01ca2b4f0b45'
 'b3b2e6d1a791d63a' 'c58bfcbacb2822d1' 'cff6d3c01e6a6bfa'
 'da403e4e3f87c9e0' 'e0770391decc44ce'] [      0  890749  899533  554843  443672  778633 1247376  910493 1503906
  935774  944558 1651575 2279775  926990 1937190 1100366  112627 2214325
 1799265  334925 2066644  918742  665847 1356277  222812  953342]


In [55]:
def get_test_features(time_series, Windows):
  
    data = []
    
    start_point = 2*max(Windows) - 1
    start_accum = sum(time_series[0:start_point])
    
    # features from tsa models
    #time_series_SARIMA_residuals = get_feature_SARIMA_residuals(time_series)
    time_series_AddES_residuals = get_feature_AddES_residuals(time_series)
    time_series_SimpleES_residuals = get_feature_SimpleES_residuals(time_series)
    time_Series_Holt_residuals = get_feature_Holt_residuals(time_series)
    
    # features from tsa models for time series logarithm
    time_series_logs = get_feature_logs(time_series)
    
    for i in np.arange(start_point, len(time_series)):        
        # the datum to put into the data pool
        datum = []        
        
        # fill the datum with f01-f09
        diff_plain = time_series[i] - time_series[i-1]
        start_accum = start_accum + time_series[i]
        mean_accum = (start_accum)/(i+1)
        
        # f01-f04: residuals
        #datum.append(time_series_SARIMA_residuals[i])
        datum.append(time_series_AddES_residuals[i])
        datum.append(time_series_SimpleES_residuals[i])
        datum.append(time_Series_Holt_residuals[i])
        # f05: logarithm
        datum.append(time_series_logs[i])
        
        # f06: diff
        datum.append(diff_plain)
        # f07: diff percentage
        datum.append(diff_plain/(time_series[i-1] + 1e-8))  # to avoid 0, plus 1e-10
        # f08: diff of diff - derivative
        datum.append(diff_plain - (time_series[i-1] - time_series[i-2]))
        # f09: diff of accumulated mean and current value
        datum.append(time_series[i] - mean_accum)

        # fill the datum with features related to windows
        # loop over different windows size to fill the datum
        for k in Windows:
            mean_w = np.mean(time_series[i-k+1:i+1])
            var_w = np.mean((np.asarray(time_series[i-k+1:i+1]) - mean_w)**2)
            #var_w = np.var(time_series[i-k:i+1])
            
            mean_w_and_1 = mean_w + (time_series[i-k]-time_series[i])/k
            var_w_and_1 = np.mean((np.asarray(time_series[i-k:i]) - mean_w_and_1)**2)
            #mean_w_and_1 = np.mean(time_series[i-k-1:i])
            #var_w_and_1 = np.var(time_series[i-k-1:i])
            
            mean_2w = np.mean(time_series[i-2*k+1:i-k+1])
            var_2w = np.mean((np.asarray(time_series[i-2*k+1:i-k+1]) - mean_2w)**2)
            #var_2w = np.var(time_series[i-2*k:i-k+1])
            
            # diff of sliding windows
            diff_mean_1 = mean_w - mean_w_and_1
            diff_var_1 = var_w - var_w_and_1
            
            # diff of jumping windows
            diff_mean_w = mean_w - mean_2w
            diff_var_w = var_w - var_2w
            
            # f1
            datum.append(mean_w)  # [0:2] is [0,1]
            # f2
            datum.append(var_w)
            # f3
            datum.append(diff_mean_1)
            # f4
            datum.append(diff_mean_1/(mean_w_and_1 + 1e-8))
            # f5
            datum.append(diff_var_1)
            # f6
            datum.append(diff_var_1/(var_w_and_1 + 1e-8))
            # f7
            datum.append(diff_mean_w)
            # f8
            datum.append(diff_mean_w/(mean_2w + 1e-8))
            # f9
            datum.append(diff_var_w)
            # f10
            datum.append(diff_var_w/(var_2w + 1e-8))
            
            # diff of sliding/jumping windows and current value
            # f11
            datum.append(time_series[i] - mean_w_and_1)
            # f12
            datum.append(time_series[i] - mean_2w)

        data.append(np.asarray(datum))
            
    return data

In [56]:
testseries_features = None
for i in range(len(testseries_scaled)):
    print(i, len(testseries_scaled[i]))
    features_temp = get_test_features(testseries_scaled[i], W)
    features_temp = scaler_list[i].transform(features_temp)
    if i==0:
        testseries_features = features_temp
    else:
        testseries_features = np.concatenate((testseries_features, features_temp), axis = 0)
    
print(testseries_features.shape)

0 112627
1 110185
2 112113
3 108747
4 111171
5 111004
6 112786
7 112116
8 8784
9 10960
10 8249
11 8248
12 8784
13 8784
14 8784
15 147024
16 147010
17 108901
18 147629
19 147669
20 147690
21 137925
22 129454
23 147681
24 65450
25 65436
(2319237, 128)


In [57]:
print(testseries_features)

[[-0.93206973 -0.93209252 -0.93206973 ... -0.398442    0.25718099
   1.0760591 ]
 [ 0.65239108  0.65236829  0.65239108 ... -0.39651193  0.46121163
   1.21466327]
 [ 0.279577    0.2795542   0.279577   ... -0.3966797   0.54603141
   1.27566771]
 ...
 [-0.22850783 -0.22859523 -0.22850783 ... -0.29360525 -1.11937186
  -0.53397675]
 [-0.48648383 -0.48657123 -0.48648383 ... -0.29232762 -1.16010143
  -0.56824054]
 [-0.18911409 -0.18920148 -0.18911409 ... -0.29098218 -1.1744739
  -0.58297141]]


In [71]:
predict_flag = (np.ravel(model.predict(testseries_features,batch_size=5000,verbose=1))>0.97).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

2319237/2319237 [==============================] - 7s 3us/step
[0 0 0 ... 0 0 0]
0.056859648237760956


In [72]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictn2.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [73]:
def new_get_timeseries_features(time_series, time_series_label, Windows, delay):
  
    data = []
    data_label = []
    data_label_vital = []
    
    start_point = 2*max(Windows) - 1
    start_accum = sum(time_series[0:start_point])
    
    time_series_AddES_residuals = get_feature_AddES_residuals(time_series)
    time_series_SimpleES_residuals = get_feature_SimpleES_residuals(time_series)
    time_Series_Holt_residuals = get_feature_Holt_residuals(time_series)
    
    for i in np.arange(start_point, len(time_series)):        
        datum = []
        datum_label = time_series_label[i]        
        
        diff_plain = time_series[i] - time_series[i-1]
        start_accum = start_accum + time_series[i]
        mean_accum = (start_accum)/(i+1)
        
        datum.append(time_series_AddES_residuals[i])
        datum.append(time_series_SimpleES_residuals[i])
        datum.append(time_Series_Holt_residuals[i])

        datum.append(time_series[i])
        

        datum.append(diff_plain)
        
        datum.append(diff_plain/(time_series[i-1] + 1e-8))  

        datum.append(diff_plain - (time_series[i-1] - time_series[i-2]))
 
        datum.append(time_series[i] - mean_accum)


        for k in Windows:
            mean_w = np.mean(time_series[i-k+1:i+1])
            var_w = np.mean((np.asarray(time_series[i-k+1:i+1]) - mean_w)**2)
 
            
            mean_w_and_1 = mean_w + (time_series[i-k]-time_series[i])/k
            var_w_and_1 = np.mean((np.asarray(time_series[i-k:i]) - mean_w_and_1)**2)

            
            mean_2w = np.mean(time_series[i-2*k+1:i-k+1])
            var_2w = np.mean((np.asarray(time_series[i-2*k+1:i-k+1]) - mean_2w)**2)
            
            
            diff_mean_1 = mean_w - mean_w_and_1
            diff_var_1 = var_w - var_w_and_1
            
            diff_mean_w = mean_w - mean_2w
            diff_var_w = var_w - var_2w
            
            datum.append(mean_w)  
            
            datum.append(var_w)
            
            datum.append(diff_mean_1)
            
            datum.append(diff_mean_1/(mean_w_and_1 + 1e-8))
            
            datum.append(diff_var_1)
            
            datum.append(diff_var_1/(var_w_and_1 + 1e-8))
            
            datum.append(diff_mean_w)
            
            datum.append(diff_mean_w/(mean_2w + 1e-8))
            
            datum.append(diff_var_w)
            
            datum.append(diff_var_w/(var_2w + 1e-8))
            
            
            datum.append(time_series[i] - mean_w_and_1)
            
            datum.append(time_series[i] - mean_2w)

        data.append(np.asarray(datum))
        data_label.append(np.asarray(datum_label))

        if datum_label == 1 and sum(time_series_label[i-delay:i]) < delay:
            data_label_vital.append(np.asarray(1))
        else:
            data_label_vital.append(np.asarray(0))
            
    return data, data_label, data_label_vital

In [76]:
scaler_list_new = [] 
timeseries_features_new = []
timeseries_features_label_new = []
timeseries_features_label_vital_new = []

for i in range(len(timeseries_all)):
    print(i,len(timeseries_all[i]),len(scaler_list_new),len(timeseries_features_new),len(timeseries_features_label_new),
                len(timeseries_features_label_vital_new))
    features_temp,label_temp,label_vital_temp = new_get_timeseries_features(timeseries_all[i], timeseries_label[i], W, delay) 
    assert(len(features_temp)==len(label_temp))
    assert(len(label_temp) == len(label_vital_temp))
    scaler_temp = StandardScaler()
    features_temp = scaler_temp.fit_transform(features_temp)
    scaler_list_new.append(scaler_temp)
    if i==0:
        timeseries_features_new = features_temp
    else:
        timeseries_features_new = np.concatenate((timeseries_features_new, features_temp), axis = 0)
        
    timeseries_features_label_new = timeseries_features_label_new + label_temp
    timeseries_features_label_vital_new = timeseries_features_label_vital_new + label_vital_temp




0 128562 0 0 0 0
1 128613 1 127563 127563 127563
2 129035 2 255177 255177 255177
3 128679 3 383213 383213 383213
4 129128 4 510893 510893 510893
5 128971 5 639022 639022 639022
6 128667 6 766994 766994 766994
7 128853 7 894662 894662 894662
8 8784 8 1022516 1022516 1022516
9 10960 9 1030301 1030301 1030301
10 8248 10 1040262 1040262 1040262
11 8247 11 1047511 1047511 1047511
12 8784 12 1054759 1054759 1054759
13 8784 13 1062544 1062544 1062544
14 8784 14 1070329 1070329 1070329
15 147024 15 1078114 1078114 1078114
16 147009 16 1224139 1224139 1224139
17 100254 17 1370149 1370149 1370149
18 147629 18 1469404 1469404 1469404
19 147668 19 1616034 1616034 1616034
20 147689 20 1762703 1762703 1762703
21 137925 21 1909393 1909393 1909393
22 129453 22 2046319 2046319 2046319
23 147680 23 2174773 2174773 2174773
24 65449 24 2321454 2321454 2321454
25 65436 25 2385904 2385904 2385904


In [426]:
file = open('train_feature.txt','wb')
pickle.dump(timeseries_features_new,file)
pickle.dump(timeseries_features_label_new,file)
pickle.dump(timeseries_features_label_vital_new,file)
pickle.dump(scaler_list_new,file)
file.close()

In [77]:
def new_get_test_features(time_series, Windows):
  
    data = []
    
    start_point = 2*max(Windows) - 1
    start_accum = sum(time_series[0:start_point])
    
    # features from tsa models
    #time_series_SARIMA_residuals = get_feature_SARIMA_residuals(time_series)
    time_series_AddES_residuals = get_feature_AddES_residuals(time_series)
    time_series_SimpleES_residuals = get_feature_SimpleES_residuals(time_series)
    time_Series_Holt_residuals = get_feature_Holt_residuals(time_series)
    
    for i in np.arange(start_point, len(time_series)):        
        # the datum to put into the data pool
        datum = []        
        
        # fill the datum with f01-f09
        diff_plain = time_series[i] - time_series[i-1]
        start_accum = start_accum + time_series[i]
        mean_accum = (start_accum)/(i+1)
        
        # f01-f04: residuals
        #datum.append(time_series_SARIMA_residuals[i])
        datum.append(time_series_AddES_residuals[i])
        datum.append(time_series_SimpleES_residuals[i])
        datum.append(time_Series_Holt_residuals[i])
        # f05: logarithm
        datum.append(time_series[i])
        
        # f06: diff
        datum.append(diff_plain)
        # f07: diff percentage
        datum.append(diff_plain/(time_series[i-1] + 1e-8))  # to avoid 0, plus 1e-10
        # f08: diff of diff - derivative
        datum.append(diff_plain - (time_series[i-1] - time_series[i-2]))
        # f09: diff of accumulated mean and current value
        datum.append(time_series[i] - mean_accum)

        # fill the datum with features related to windows
        # loop over different windows size to fill the datum
        for k in Windows:
            mean_w = np.mean(time_series[i-k+1:i+1])
            var_w = np.mean((np.asarray(time_series[i-k+1:i+1]) - mean_w)**2)
            #var_w = np.var(time_series[i-k:i+1])
            
            mean_w_and_1 = mean_w + (time_series[i-k]-time_series[i])/k
            var_w_and_1 = np.mean((np.asarray(time_series[i-k:i]) - mean_w_and_1)**2)
            #mean_w_and_1 = np.mean(time_series[i-k-1:i])
            #var_w_and_1 = np.var(time_series[i-k-1:i])
            
            mean_2w = np.mean(time_series[i-2*k+1:i-k+1])
            var_2w = np.mean((np.asarray(time_series[i-2*k+1:i-k+1]) - mean_2w)**2)
            #var_2w = np.var(time_series[i-2*k:i-k+1])
            
            # diff of sliding windows
            diff_mean_1 = mean_w - mean_w_and_1
            diff_var_1 = var_w - var_w_and_1
            
            # diff of jumping windows
            diff_mean_w = mean_w - mean_2w
            diff_var_w = var_w - var_2w
            
            # f1
            datum.append(mean_w)  # [0:2] is [0,1]
            # f2
            datum.append(var_w)
            # f3
            datum.append(diff_mean_1)
            # f4
            datum.append(diff_mean_1/(mean_w_and_1 + 1e-8))
            # f5
            datum.append(diff_var_1)
            # f6
            datum.append(diff_var_1/(var_w_and_1 + 1e-8))
            # f7
            datum.append(diff_mean_w)
            # f8
            datum.append(diff_mean_w/(mean_2w + 1e-8))
            # f9
            datum.append(diff_var_w)
            # f10
            datum.append(diff_var_w/(var_2w + 1e-8))
            
            # diff of sliding/jumping windows and current value
            # f11
            datum.append(time_series[i] - mean_w_and_1)
            # f12
            datum.append(time_series[i] - mean_2w)

        data.append(np.asarray(datum))
            
    return data

In [79]:
testseries_features_new = []
for i in range(len(testseries_all)):
    print(i, len(testseries_all[i]), len(testseries_features_new))
    features_temp = new_get_test_features(testseries_all[i], W)
    features_temp = scaler_list_new[i].transform(features_temp)
    if i==0:
        testseries_features_new = features_temp
    else:
        testseries_features_new = np.concatenate((testseries_features_new, features_temp), axis = 0)
    
print(testseries_features_new.shape)

0 112627 0
1 110185 111628
2 112113 220814
3 108747 331928
4 111171 439676
5 111004 549848
6 112786 659853
7 112116 771640
8 8784 882757
9 10960 890542
10 8249 900503
11 8248 907753
12 8784 915002
13 8784 922787
14 8784 930572
15 147024 938357
16 147010 1084382
17 108901 1230393
18 147629 1338295
19 147669 1484925
20 147690 1631595
21 137925 1778286
22 129454 1915212
23 147681 2043667
24 65450 2190349
25 65436 2254800
(2319237, 128)


In [427]:
file = open('test_feature.txt','wb')
pickle.dump(testseries_features_new,file)
file.close()

In [81]:
timeseries_features_label_new = np.array(timeseries_features_label_new)
timeseries_features_label_vital_new = np.array(timeseries_features_label_vital_new)

In [82]:
ratio = round((len(timeseries_features_label_new) - sum(timeseries_features_label_new)) * 0.5 / sum(timeseries_features_label_new))
print(ratio)
non_anomaly = np.ones(len(timeseries_features_label_new)) - timeseries_features_label_new
print(non_anomaly,non_anomaly.shape)
sample_ratio = (4*ratio) * timeseries_features_label_vital_new + non_anomaly
print(sample_ratio,sum(sample_ratio))
sample_ratio = sample_ratio + ratio * timeseries_features_label_new
print(sample_ratio,sum(sample_ratio))

23.0
[1. 1. 1. ... 0. 0. 0.] (2450341,)
[1. 1. 1. ... 0. 0. 0.] 2843598.0
[ 1.  1.  1. ... 23. 23. 23.] 4067635.0


In [84]:
print('Keras: start to train DNN!')
start_time = time.time()
history = model.fit(timeseries_features_new, timeseries_features_label_new, epochs=20, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.1081 - acc: 0.9837 - binary_accuracy: 0.9837
Epoch 2/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.1091 - acc: 0.9840 - binary_accuracy: 0.9840
Epoch 3/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.1076 - acc: 0.9841 - binary_accuracy: 0.9841
Epoch 4/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.1024 - acc: 0.9843 - binary_accuracy: 0.9843
Epoch 5/20
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.1055 - acc: 0.9841 - binary_accuracy: 0.9841
Epoch 6/20
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.1048 - acc: 0.9844 - binary_accuracy: 0.9844
Epoch 7/20
2450341/2450341 [==============================] - 33s 14us/step - loss: 0.1016 - acc: 0.9847 - binary_accuracy: 0.9847
Epoch 8/20
2450341/2450341 [============================

In [88]:
train_data_check = np.ravel(model.predict(timeseries_features, batch_size=5000,verbose=1)>0.95).astype(int)
print(train_data_check)
print(precision_score(timeseries_features_label, train_data_check))
print(recall_score(timeseries_features_label, train_data_check))
print(f1_score(timeseries_features_label, train_data_check))

2450341/2450341 [==============================] - 7s 3us/step
[0 0 0 ... 1 1 1]
0.9505989166094453
0.9364700576861648
0.9434815943661438


In [95]:
predict_flag = (np.ravel(model.predict(testseries_features_new,batch_size=5000,verbose=1))>0.999).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

2319237/2319237 [==============================] - 6s 3us/step
[0 0 0 ... 0 0 0]
0.014157242230957854


In [96]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictn4.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [97]:
ratio = round((len(timeseries_features_label_new) - sum(timeseries_features_label_new)) * 0.2 / sum(timeseries_features_label_new))
print(ratio)
non_anomaly = np.ones(len(timeseries_features_label_new)) - timeseries_features_label_new
print(non_anomaly,non_anomaly.shape)
sample_ratio = (4*ratio) * timeseries_features_label_vital_new + non_anomaly
print(sample_ratio,sum(sample_ratio))
sample_ratio = sample_ratio + ratio * timeseries_features_label_new
print(sample_ratio,sum(sample_ratio))

9.0
[1. 1. 1. ... 0. 0. 0.] (2450341,)
[1. 1. 1. ... 0. 0. 0.] 2571830.0
[1. 1. 1. ... 9. 9. 9.] 3050801.0


In [98]:
print('Keras: start to train DNN!')
start_time = time.time()
history = model.fit(timeseries_features_new, timeseries_features_label_new, epochs=20, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0567 - acc: 0.9913 - binary_accuracy: 0.9913
Epoch 2/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0566 - acc: 0.9922 - binary_accuracy: 0.9922
Epoch 3/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0539 - acc: 0.9923 - binary_accuracy: 0.9923
Epoch 4/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0559 - acc: 0.9921 - binary_accuracy: 0.9921
Epoch 5/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0540 - acc: 0.9926 - binary_accuracy: 0.9926
Epoch 6/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0532 - acc: 0.9926 - binary_accuracy: 0.9926
Epoch 7/20
2450341/2450341 [==============================] - 34s 14us/step - loss: 0.0540 - acc: 0.9925 - binary_accuracy: 0.9925
Epoch 8/20
2450341/2450341 [============================

In [102]:
train_data_check = np.ravel(model.predict(timeseries_features, batch_size=5000,verbose=1)>0.9).astype(int)
print(train_data_check)
print(precision_score(timeseries_features_label, train_data_check))
print(recall_score(timeseries_features_label, train_data_check))
print(f1_score(timeseries_features_label, train_data_check))

2450341/2450341 [==============================] - 7s 3us/step
[0 0 0 ... 1 1 1]
0.9635409659625992
0.9420319810593961
0.952665083135392


In [107]:
predict_flag = (np.ravel(model.predict(testseries_features_new,batch_size=5000,verbose=1))>0.99).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

2319237/2319237 [==============================] - 6s 3us/step
[0 0 0 ... 0 0 0]
0.018293085182756224


In [108]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictn5.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [112]:
from keras.regularizers import l1
help(l1)

Help on function l1 in module keras.regularizers:

l1(l=0.01)



In [386]:
m = Sequential()
m.add(Dense(128, input_dim = 128))
m.add(BatchNormalization())
m.add(Activation('relu'))
m.add(Dropout(0.5))

m.add(Dense(64))
m.add(BatchNormalization())
m.add(Activation('relu'))
m.add(Dropout(0.5))

m.add(Dense(1))
m.add(BatchNormalization())
m.add(Activation('sigmoid'))


m.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])

In [388]:
ratio = round((len(timeseries_features_label_new) - sum(timeseries_features_label_new)) * 0.8 / sum(timeseries_features_label_new))
print(ratio)
non_anomaly = np.ones(len(timeseries_features_label_new)) - timeseries_features_label_new
print(non_anomaly,non_anomaly.shape)
sample_ratio = (4*ratio) * timeseries_features_label_vital_new + non_anomaly
print(sample_ratio,sum(sample_ratio))
sample_ratio = sample_ratio + ratio * timeseries_features_label_new
print(sample_ratio,sum(sample_ratio))

36.0
[1. 1. 1. ... 0. 0. 0.] (2450341,)
[1. 1. 1. ... 0. 0. 0.] 3095954.0
[ 1.  1.  1. ... 36. 36. 36.] 5011838.0


In [389]:
print('Keras: start to train DNN!')
start_time = time.time()
h = m.fit(timeseries_features_new, timeseries_features_label_new, epochs=50, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/50
2450341/2450341 [==============================] - 27s 11us/step - loss: 0.9429 - binary_accuracy: 0.7647
Epoch 2/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.7383 - binary_accuracy: 0.8635
Epoch 3/50
2450341/2450341 [==============================] - 21s 9us/step - loss: 0.6438 - binary_accuracy: 0.8969
Epoch 4/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.5818 - binary_accuracy: 0.9128
Epoch 5/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.5387 - binary_accuracy: 0.9228
Epoch 6/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.5068 - binary_accuracy: 0.9301
Epoch 7/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.4881 - binary_accuracy: 0.9345
Epoch 8/50
2450341/2450341 [==============================] - 21s 8us/step - loss: 0.4717 - binary_accuracy: 0.9371
Epoch 9/50
2450341/2450341 [================

In [332]:
p = m.predict(timeseries_features_new, batch_size=5000,verbose=1)

2450341/2450341 [==============================] - 8s 3us/step


In [336]:
train_data_check = np.ravel(p>0.95).astype(int)
print(train_data_check)
print(precision_score(timeseries_features_label, train_data_check))
print(recall_score(timeseries_features_label, train_data_check))
print(f1_score(timeseries_features_label, train_data_check))

[0 0 0 ... 0 0 0]
0.8598601499945654
0.44594975478682425
0.587305122494432


In [251]:
print(len(train_data_check))
print(len(train_data))

2450341
2476315


In [338]:
last_index = 0
evaluation_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(timeseries_all)):
    next_index += len(timeseries_all[i]) - data_features_diff_avg
    evaluation_new = np.concatenate((evaluation_new, train_data_check[last_index : next_index]))
    print(len(evaluation_new),next_index)
    last_index = next_index
    if i != len(timeseries_all)-1:
        evaluation_new = np.concatenate((evaluation_new,np.zeros(data_features_diff_avg)))
print(len(evaluation_new))
assert(len(evaluation_new) == len(train_data))
evaluation_new = evaluation_new.astype(int)
evaluation_df = pd.DataFrame({'KPI ID': train_data['KPI ID'], 
                         'timestamp': train_data['timestamp'], 
                         'predict': evaluation_new})
evaluation_df.to_csv('evaluation.csv', index=False)

128562 127563
257175 255177
386210 383213
514889 510893
644017 639022
772988 766994
901655 894662
1030508 1022516
1039292 1030301
1050252 1040262
1058500 1047511
1066747 1054759
1075531 1062544
1084315 1070329
1093099 1078114
1240123 1224139
1387132 1370149
1487386 1469404
1635015 1616034
1782683 1762703
1930372 1909393
2068297 2046319
2197750 2174773
2345430 2321454
2410879 2385904
2476315 2450341
2476315


In [339]:
!python evaluation.py "../../input/train.csv" "evaluation.csv" 7

OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0
OMP: Info #156: KMP_AFFINITY: 1 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 1 packages x 1 cores/pkg x 1 threads/core (1 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 
OMP: Info #250: KMP_AFFINITY: pid 15953 tid 15953 thread 0 bound to OS proc set 0
{"result": true, "data": 0.5535412621971205, "message": "计算成功"}


In [390]:
pm_t = m.predict(testseries_features_new,batch_size=5000,verbose=1)

2319237/2319237 [==============================] - 7s 3us/step


In [395]:
predict_flagm = (np.ravel(pm_t)>0.9985).astype(int)
print(predict_flagm)
print(sum(predict_flagm)/len(predict_flagm))

[0 0 0 ... 0 0 0]
0.008406212905364998


In [396]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flagm[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictw2.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [152]:
test = Sequential()
test.add(Dense(128, input_dim = 128, kernel_regularizer=l1(0.05)))
test.add(BatchNormalization())
test.add(Activation('relu'))
test.add(Dropout(0.2))

test.add(Dense(128, kernel_regularizer=l1(0.05)))
test.add(BatchNormalization())
test.add(Activation('relu'))
test.add(Dropout(0.2))

test.add(Dense(1))
test.add(BatchNormalization())
test.add(Activation('sigmoid'))


test.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])

In [153]:
print('Keras: start to train DNN!')
start_time = time.time()
h_t = test.fit(timeseries_features_new, timeseries_features_label_new, epochs=100, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/100
2450341/2450341 [==============================] - 28s 12us/step - loss: 16.9901 - binary_accuracy: 0.7321
Epoch 2/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.7455 - binary_accuracy: 0.8211
Epoch 3/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.5959 - binary_accuracy: 0.8328
Epoch 4/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.5670 - binary_accuracy: 0.8379
Epoch 5/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.5445 - binary_accuracy: 0.8421
Epoch 6/100
2450341/2450341 [==============================] - 24s 10us/step - loss: 1.5064 - binary_accuracy: 0.8388
Epoch 7/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.5098 - binary_accuracy: 0.8362
Epoch 8/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.4633 - binary_accuracy: 0.8396
Epoch 9/100
2450341/2450341 

In [154]:
t1 = Sequential()
t1.add(Dense(128, input_dim = 128, kernel_regularizer=l1(0.1)))
t1.add(BatchNormalization())
t1.add(Activation('relu'))
t1.add(Dropout(0.2))

t1.add(Dense(128, kernel_regularizer=l1(0.1)))
t1.add(BatchNormalization())
t1.add(Activation('relu'))
t1.add(Dropout(0.2))

t1.add(Dense(1))
t1.add(BatchNormalization())
t1.add(Activation('sigmoid'))


t1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])

In [155]:
print('Keras: start to train DNN!')
start_time = time.time()
h_t1 = t1.fit(timeseries_features_new, timeseries_features_label_new, epochs=100, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/100
2450341/2450341 [==============================] - 28s 12us/step - loss: 29.8404 - binary_accuracy: 0.7187
Epoch 2/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.9888 - binary_accuracy: 0.8087
Epoch 3/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.9249 - binary_accuracy: 0.8315
Epoch 4/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.8623 - binary_accuracy: 0.8372
Epoch 5/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.7749 - binary_accuracy: 0.8334
Epoch 6/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.8153 - binary_accuracy: 0.8325
Epoch 7/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.8095 - binary_accuracy: 0.8360
Epoch 8/100
2450341/2450341 [==============================] - 25s 10us/step - loss: 1.6953 - binary_accuracy: 0.8345
Epoch 9/100
2450341/2450341 

In [277]:
print(timeseries_features_new.shape)
print(testseries_features_new.shape)

(2450341, 128)
(2319237, 128)


In [280]:
for i in range(len(scaler_list_new)):
    print(scaler_list_new[i].mean_, scaler_list_new[i].var_)

[ 7.31490319e-06  1.15616180e-05  7.31490319e-06  1.94693803e+00
  1.15616180e-05  4.80487943e-03 -1.92543333e-06 -1.07310891e-02
  1.94693225e+00  1.04023104e-02  1.25243347e-05  2.03071919e-03
  1.18228370e-07  3.26021319e+04  2.52730025e-05  5.12386077e-03
  1.39358402e-07  5.03469111e+04  1.83051437e-05  3.10538115e-05
  1.94691372e+00  2.42435890e-02  1.22141007e-05  4.34735801e-04
  4.30472062e-08  6.65788249e+02  5.85065655e-05  4.15036881e-03
  5.24113795e-07  9.88633839e+03  3.65214554e-05  8.28139202e-05
  1.94688447e+00  3.25345479e-02  1.19198745e-05  1.29097877e-04
  8.62630058e-08  3.26284234e+01  1.16814951e-04  3.53093725e-03
  2.80210169e-06  1.52484960e+03  6.54805120e-05  1.70375588e-04
  1.94679561e+00  4.14839491e-02  1.20202948e-05  3.22326955e-05
  2.47354161e-07  8.73884756e-01  2.92743303e-04  4.34386068e-03
  3.08897323e-06  1.04461288e+02  1.54436068e-04  4.35159076e-04
  1.94664924e+00  4.86315837e-02  1.12977645e-05  1.50448778e-05
  4.40078534e-08  8.97180

In [282]:
help(StandardScaler.inverse_transform)
print(data_features_diff_avg)

Help on function inverse_transform in module sklearn.preprocessing.data:

inverse_transform(self, X, copy=None)
    Scale back the data to the original representation
    
    Parameters
    ----------
    X : array-like, shape [n_samples, n_features]
        The data used to scale along the features axis.
    copy : bool, optional (default: None)
        Copy the input X or not.
    
    Returns
    -------
    X_tr : array-like, shape [n_samples, n_features]
        Transformed array.

999


In [284]:
train_feature = None
index1 = 0
index2 = 0
for i in range(len(scaler_list_new)):
    index2 += len(timeseries_all[i]) - data_features_diff_avg
    temp = timeseries_features_new[index1:index2,]
    print(temp.shape)
    temp = scaler_list_new[i].inverse_transform(temp)
    if i == 0:
        train_feature = temp
    else:
        train_feature = np.concatenate((train_feature, temp), axis = 0)
    index1 = index2
    print(train_feature.shape)

(127563, 128)
(127563, 128)
(127614, 128)
(255177, 128)
(128036, 128)
(383213, 128)
(127680, 128)
(510893, 128)
(128129, 128)
(639022, 128)
(127972, 128)
(766994, 128)
(127668, 128)
(894662, 128)
(127854, 128)
(1022516, 128)
(7785, 128)
(1030301, 128)
(9961, 128)
(1040262, 128)
(7249, 128)
(1047511, 128)
(7248, 128)
(1054759, 128)
(7785, 128)
(1062544, 128)
(7785, 128)
(1070329, 128)
(7785, 128)
(1078114, 128)
(146025, 128)
(1224139, 128)
(146010, 128)
(1370149, 128)
(99255, 128)
(1469404, 128)
(146630, 128)
(1616034, 128)
(146669, 128)
(1762703, 128)
(146690, 128)
(1909393, 128)
(136926, 128)
(2046319, 128)
(128454, 128)
(2174773, 128)
(146681, 128)
(2321454, 128)
(64450, 128)
(2385904, 128)
(64437, 128)
(2450341, 128)


In [285]:
scaler_new = StandardScaler()
train_feature = scaler_new.fit_transform(train_feature)
print(train_feature)

[[ 3.33424271e-06  3.33067411e-06  3.33424271e-06 ... -1.10451253e-02
   4.47285694e-04  5.72909585e-05]
 [ 3.33023637e-06  3.32666778e-06  3.33023637e-06 ... -1.10450991e-02
   4.47284249e-04  5.72898743e-05]
 [ 3.33424271e-06  3.33067411e-06  3.33424271e-06 ... -1.10450668e-02
   4.47284330e-04  5.72898430e-05]
 ...
 [ 3.33410445e-06  3.33053563e-06  3.33410445e-06 ... -1.10465265e-02
   4.47326071e-04  5.73205080e-05]
 [ 3.33422634e-06  3.33065752e-06  3.33422634e-06 ... -1.10465272e-02
   4.47326057e-04  5.73205133e-05]
 [ 3.33418061e-06  3.33061179e-06  3.33418061e-06 ... -1.10465280e-02
   4.47326025e-04  5.73205065e-05]]


In [286]:
test_feature = None
index1 = 0
index2 = 0
for i in range(len(scaler_list_new)):
    index2 += len(testseries_all[i]) - data_features_diff_avg
    temp = testseries_features_new[index1:index2,]
    print(temp.shape)
    temp = scaler_list_new[i].inverse_transform(temp)
    if i == 0:
        test_feature = temp
    else:
        test_feature = np.concatenate((test_feature, temp), axis = 0)
    index1 = index2
    print(test_feature.shape)

(111628, 128)
(111628, 128)
(109186, 128)
(220814, 128)
(111114, 128)
(331928, 128)
(107748, 128)
(439676, 128)
(110172, 128)
(549848, 128)
(110005, 128)
(659853, 128)
(111787, 128)
(771640, 128)
(111117, 128)
(882757, 128)
(7785, 128)
(890542, 128)
(9961, 128)
(900503, 128)
(7250, 128)
(907753, 128)
(7249, 128)
(915002, 128)
(7785, 128)
(922787, 128)
(7785, 128)
(930572, 128)
(7785, 128)
(938357, 128)
(146025, 128)
(1084382, 128)
(146011, 128)
(1230393, 128)
(107902, 128)
(1338295, 128)
(146630, 128)
(1484925, 128)
(146670, 128)
(1631595, 128)
(146691, 128)
(1778286, 128)
(136926, 128)
(1915212, 128)
(128455, 128)
(2043667, 128)
(146682, 128)
(2190349, 128)
(64451, 128)
(2254800, 128)
(64437, 128)
(2319237, 128)


In [287]:
test_feature = scaler_new.transform(test_feature)
print(test_feature)

[[ 3.31995145e-06  3.31638251e-06  3.31995145e-06 ... -1.10462739e-02
   4.47330416e-04  5.73421658e-05]
 [ 3.34424717e-06  3.34067823e-06  3.34424717e-06 ... -1.10462716e-02
   4.47334149e-04  5.73448953e-05]
 [ 3.33853054e-06  3.33496160e-06  3.33853054e-06 ... -1.10462718e-02
   4.47335700e-04  5.73460966e-05]
 ...
 [ 3.33412088e-06  3.33055199e-06  3.33412088e-06 ... -1.10461196e-02
   4.47323109e-04  5.73197949e-05]
 [ 3.33398312e-06  3.33041424e-06  3.33398312e-06 ... -1.10461077e-02
   4.47323015e-04  5.73197205e-05]
 [ 3.33414191e-06  3.33057303e-06  3.33414191e-06 ... -1.10460951e-02
   4.47322982e-04  5.73196885e-05]]


In [297]:
m = Sequential()
m.add(Dense(512, input_dim = 128))
m.add(BatchNormalization())
m.add(Activation('relu'))
m.add(Dropout(0.2))

m.add(Dense(256))
m.add(BatchNormalization())
m.add(Activation('relu'))
m.add(Dropout(0.2))

m.add(Dense(1))
m.add(BatchNormalization())
m.add(Activation('sigmoid'))


m.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])

In [289]:
ratio = round((len(timeseries_features_label_new) - sum(timeseries_features_label_new)) * 0.8 / sum(timeseries_features_label_new))
print(ratio)
non_anomaly = np.ones(len(timeseries_features_label_new)) - timeseries_features_label_new
print(non_anomaly,non_anomaly.shape)
sample_ratio = (4*ratio) * timeseries_features_label_vital_new + non_anomaly
print(sample_ratio,sum(sample_ratio))
sample_ratio = sample_ratio + ratio * timeseries_features_label_new
print(sample_ratio,sum(sample_ratio))

36.0
[1. 1. 1. ... 0. 0. 0.] (2450341,)
[1. 1. 1. ... 0. 0. 0.] 3095954.0
[ 1.  1.  1. ... 36. 36. 36.] 5011838.0


In [290]:
print(len(train_feature),len(timeseries_features_label),len(sample_ratio))

2450341 2450341 2450341


In [298]:
print('Keras: start to train DNN!')
start_time = time.time()
h = m.fit(train_feature, timeseries_features_label_new, epochs=10, batch_size=5000, verbose=1,
                   sample_weight=sample_ratio)

end_time = time.time()
print('It took %d seconds to train the model!' %(end_time-start_time))

Keras: start to train DNN!
Epoch 1/10
2450341/2450341 [==============================] - 79s 32us/step - loss: 1.3566 - binary_accuracy: 0.1367
Epoch 2/10
2450341/2450341 [==============================] - 73s 30us/step - loss: 1.3345 - binary_accuracy: 0.1974
Epoch 3/10
 545000/2450341 [=====>........................] - ETA: 56s - loss: 1.3227 - binary_accuracy: 0.2558

KeyboardInterrupt: 

In [345]:
import xgboost as xgb

In [347]:
help(xgb.DMatrix)

Help on class DMatrix in module xgboost.core:

class DMatrix(builtins.object)
 |  DMatrix(data, label=None, missing=None, weight=None, silent=False, feature_names=None, feature_types=None, nthread=None)
 |  
 |  Data Matrix used in XGBoost.
 |  
 |  DMatrix is a internal data structure that used by XGBoost
 |  which is optimized for both memory efficiency and training speed.
 |  You can construct DMatrix from numpy.arrays
 |  
 |  Methods defined here:
 |  
 |  __del__(self)
 |  
 |  __init__(self, data, label=None, missing=None, weight=None, silent=False, feature_names=None, feature_types=None, nthread=None)
 |      Parameters
 |      ----------
 |      data : string/numpy.array/scipy.sparse/pd.DataFrame/dt.Frame
 |          Data source of DMatrix.
 |          When data is string type, it represents the path libsvm format txt file,
 |          or binary file that xgboost can read from.
 |      label : list or numpy 1-D array, optional
 |          Label of the training data.
 |      mi

In [353]:
xgb_model = xgb.XGBClassifier(n_jobs=4, verbosity=1, silent = 0)

In [354]:
xgb_model.fit(timeseries_features_new, timeseries_features_label_new, sample_weight = sample_ratio, verbose = True)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=4,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [369]:
y_p = xgb_model.predict_proba(timeseries_features_new)

In [373]:
train_data_check = (np.ravel(y_p[:,1:])>0.85).astype(int)
print(train_data_check)
print(sum(train_data_check)/len(train_data_check))
print(precision_score(timeseries_features_label, train_data_check))
print(recall_score(timeseries_features_label, train_data_check))
print(f1_score(timeseries_features_label, train_data_check))

[0 0 0 ... 0 0 0]
0.02038777459953533
0.7979662509758392
0.7490557883462673
0.7727378460107001


In [374]:
last_index = 0
evaluation_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(timeseries_all)):
    next_index += len(timeseries_all[i]) - data_features_diff_avg
    evaluation_new = np.concatenate((evaluation_new, train_data_check[last_index : next_index]))
    print(len(evaluation_new),next_index)
    last_index = next_index
    if i != len(timeseries_all)-1:
        evaluation_new = np.concatenate((evaluation_new,np.zeros(data_features_diff_avg)))
print(len(evaluation_new))
assert(len(evaluation_new) == len(train_data))
evaluation_new = evaluation_new.astype(int)
evaluation_df = pd.DataFrame({'KPI ID': train_data['KPI ID'], 
                         'timestamp': train_data['timestamp'], 
                         'predict': evaluation_new})
evaluation_df.to_csv('evaluation.csv', index=False)

128562 127563
257175 255177
386210 383213
514889 510893
644017 639022
772988 766994
901655 894662
1030508 1022516
1039292 1030301
1050252 1040262
1058500 1047511
1066747 1054759
1075531 1062544
1084315 1070329
1093099 1078114
1240123 1224139
1387132 1370149
1487386 1469404
1635015 1616034
1782683 1762703
1930372 1909393
2068297 2046319
2197750 2174773
2345430 2321454
2410879 2385904
2476315 2450341
2476315


In [375]:
!python evaluation.py "../../input/train.csv" "evaluation.csv" 7

OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0
OMP: Info #156: KMP_AFFINITY: 1 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 1 packages x 1 cores/pkg x 1 threads/core (1 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 
OMP: Info #250: KMP_AFFINITY: pid 32039 tid 32039 thread 0 bound to OS proc set 0
{"result": true, "data": 0.8365076751376767, "message": "计算成功"}


In [376]:
p_t = xgb_model.predict_proba(testseries_features_new)

In [384]:
predict_flag = (np.ravel(p_t[:,1:])>0.93).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

[0 0 0 ... 0 0 0]
0.007940111338341015


In [385]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictx4.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [417]:
predict_flagm = (np.ravel(pm_t)>0.99).astype(int)
print(predict_flagm)
print(sum(predict_flagm)/len(predict_flagm))

[0 0 0 ... 0 0 0]
0.016826654628224715


In [418]:
temp1 = np.ravel(pm_t) - 0.49
print(temp1)

[-0.32250184 -0.42262426 -0.39404276 ... -0.45441595 -0.4576002
 -0.4510805 ]


In [413]:
predict_flag = (np.ravel(p_t[:,1:])>0.85).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

[0 0 0 ... 0 0 0]
0.014869114281981531


In [414]:
temp2 = np.ravel(p_t[:,1:])- 0.35
print(temp2)

[-0.23618336 -0.13017786 -0.154143   ...  0.33845142  0.36765185
  0.3452185 ]


In [421]:
predict_flag = ((temp1*0.4 + temp2 * 0.6)>0.5).astype(int)
print(predict_flag)
print(sum(predict_flag)/len(predict_flag))

[0 0 0 ... 0 0 0]
0.008550225785463064


In [422]:
last_index = 0
predict_new = np.zeros(data_features_diff_avg).astype(int)
next_index = 0
for i in range(len(testseries_all)):
    next_index += len(testseries_all[i]) - data_features_diff_avg
    predict_new = np.concatenate((predict_new, predict_flag[last_index : next_index]))
    print(next_index)
    last_index = next_index
    if i != len(testseries_all)-1:
        predict_new = np.concatenate((predict_new,np.zeros(data_features_diff_avg)))
print(len(predict_new))
assert(len(predict_new) == len(test_data))
predict_new = predict_new.astype(int)
predict_df = pd.DataFrame({'KPI ID': test_data['KPI ID'], 
                         'timestamp': test_data['timestamp'], 
                         'predict': predict_new})
predict_df.to_csv('predictu2.csv', index=False)

111628
220814
331928
439676
549848
659853
771640
882757
890542
900503
907753
915002
922787
930572
938357
1084382
1230393
1338295
1484925
1631595
1778286
1915212
2043667
2190349
2254800
2319237
2345211


In [423]:
file = open('firstModel.txt','wb')
pickle.dump(m,file)
file.close()

In [424]:
file = open('xgboost.txt','wb')
pickle.dump(xgb_model,file)
file.close()

In [431]:
sp = np.where(timeseries_label[1:]!=timeseries_label[:-1])
print(sp)

(array([0]),)


/root/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [432]:
timeseries_label[1:]!=timeseries_label[:-1]

/root/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


True

In [440]:
test_array = np.array([0,1,0,1,1,0,1,1,1,0,0,0])

In [438]:
test_array[1:]!=test_array[:-1]

array([False, False,  True, False,  True,  True, False, False,  True,
       False, False])

In [441]:
np.where(test_array[1:]!=test_array[:-1])[0]

array([0, 1, 2, 4, 5, 8])

In [2]:
import xgboost as xgb
help(xgb.XGBClassifier)

Help on class XGBClassifier in module xgboost.sklearn:

class XGBClassifier(XGBModel, sklearn.base.ClassifierMixin)
 |  XGBClassifier(max_depth=3, learning_rate=0.1, n_estimators=100, verbosity=1, silent=None, objective='binary:logistic', booster='gbtree', n_jobs=1, nthread=None, gamma=0, min_child_weight=1, max_delta_step=0, subsample=1, colsample_bytree=1, colsample_bylevel=1, colsample_bynode=1, reg_alpha=0, reg_lambda=1, scale_pos_weight=1, base_score=0.5, random_state=0, seed=None, missing=None, **kwargs)
 |  
 |  Implementation of the scikit-learn API for XGBoost classification.
 |  
 |  Parameters
 |  ----------
 |  max_depth : int
 |      Maximum tree depth for base learners.
 |  learning_rate : float
 |      Boosting learning rate (xgb's "eta")
 |  n_estimators : int
 |      Number of trees to fit.
 |  verbosity : int
 |      The degree of verbosity. Valid values are 0 (silent) - 3 (debug).
 |  silent : boolean
 |      Whether to print messages while running boosting. Deprecat